name: Itemex
version: '${project.version}'
main: sh.ome.itemex.Itemex
api-version: 1.19
authors: [ oMesh_ ]
description: Item Exchange System - Trade all Items on a free market
website: ome.sh
commands:
  ix:
    description: Itemex commands overview
    usage: /<command> <price/buy/sell> <market/limit/stoplimit> <itemname> <amount>
  i:
    description: Itemex simple commands overview
    usage: /<command> <parameter>
permissions:
  itemex.command.ix:
    description: global command
    default: true
  itemex.command.ix.help:
    description: prints out the help message
    default: true
  itemex.command.ix.price:
    description: prints the current buy and sell orders
    default: true
  itemex.command.ix.buy:
    description: creates buy order
    default: true
  itemex.command.ix.sell:
    description: creates sell order
    default: true
  itemex.command.ix.withdraw:
    description: list or withdraw all your available payouts
    default: true
  itemex.command.ix.deposit:
      description: deposit items from your inventory
      default: true
  itemex.command.ix.order.list:
    description: list all own buy- and sellorders
    default: true
  itemex.command.ix.order.close:
    description: close your specific order
    default: true
  itemex.command.ix.gui:
    description: Graphical User Interface
    default: true
  itemex.command.ix.setting:
    description: User settings
    default: true
  itemex.command.ix.whatIsInMyRightHand:
    description: prints out the item name
    default: true
  itemex.command.ix.send:
    description: send items to other players
    default: true
  itemex.command.ix.stats:
      description: print stats about buy- and sellorders
      default: true
  itemex.command.price:
    description: Prints the current buy and sell orders
    default: true


    itemex.command.i:
      description: global command
      default: true

